<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_foto_document</name>
   <tag></tag>
   <elementGuidId>4a5f4465-1196-466b-96cb-b9cddc6a41b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pr_id_158_header_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='pr_id_158_header_2']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@role = 'tab' and @class = 'p-tabview-nav-link' and (text() = 'Foto &amp; Document' or . = 'Foto &amp; Document')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7888911c-7cbf-48af-8c67-71840b1ba444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>19397305-0a5f-4d8a-804c-706441ef77c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-tabview-nav-link</value>
      <webElementGuid>921408fd-539c-4fb8-899b-8a04c7b48d59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pr_id_158_header_2</value>
      <webElementGuid>177dbaba-f43c-471f-b52b-8a743475f9a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>pr_id_158_content_2</value>
      <webElementGuid>e38eb7d1-fd1a-4d02-88af-97ea68cd327c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>64038c6d-2cd3-48cb-a12b-3391930617c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>97f5ea6c-dafe-4256-8536-3c84f6dec9fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Foto &amp; Document</value>
      <webElementGuid>869c16ba-55c3-4f73-8de9-404d336aef7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_158_header_2&quot;)</value>
      <webElementGuid>8c0cf021-721e-4e2d-84cf-ff426c5fc8e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='pr_id_158_header_2']</value>
      <webElementGuid>9530b7dc-4983-41fd-817b-3905ac3de4c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_158']/ul/li[3]/a</value>
      <webElementGuid>f5af372c-b2aa-456f-8313-dacbe1ea0f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Medical Plan'])[2]/following::a[1]</value>
      <webElementGuid>24479ee9-99eb-413a-ac5c-75c0ed1b2a0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diagnosis'])[1]/following::a[2]</value>
      <webElementGuid>e89938b6-5c55-4fcb-afb1-5592a638b33c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prescription'])[1]/preceding::a[1]</value>
      <webElementGuid>d10e137a-19ed-41a2-a9f6-2130fcd037dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[3]/a</value>
      <webElementGuid>7fb0e47d-8063-4f70-b251-c5b60a9ca449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'pr_id_158_header_2' and (text() = 'Foto &amp; Document' or . = 'Foto &amp; Document')]</value>
      <webElementGuid>3c6a4a76-b1c9-4157-81d0-c2158392d2b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
