<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_photo_document</name>
   <tag></tag>
   <elementGuidId>4c987d33-7d83-449f-89c7-394511a92277</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pr_id_158_header_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='pr_id_158_header_2']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@role = 'tab' and @class = 'p-tabview-nav-link' and (text() = 'Photo &amp; Document' or . = 'Photo &amp; Document')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>de1e7dfa-dff7-49ae-ab42-aba00a3ee8b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>2eee46e3-300e-4179-871a-33134dfcd7d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-tabview-nav-link</value>
      <webElementGuid>54406399-1adc-4d1a-b8f3-81421f4d5d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pr_id_158_header_2</value>
      <webElementGuid>629bc190-740a-4276-bb99-06e302417c71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>pr_id_158_content_2</value>
      <webElementGuid>4d79bf3b-5e9f-4afe-bf45-c930839b6f03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f2dce011-3560-4d57-9791-40cb1c2e36c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>31d202e4-2238-440b-9430-a3b7be59b663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Photo &amp; Document</value>
      <webElementGuid>27078600-2832-4b3d-a1b4-80a4263d95f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_158_header_2&quot;)</value>
      <webElementGuid>932cdf35-5dda-4b80-a7c9-b673da2d909e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='pr_id_158_header_2']</value>
      <webElementGuid>9c5a9ca1-8b3a-4381-91d3-fbe3dd8ec434</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_158']/ul/li[3]/a</value>
      <webElementGuid>56804009-5e0d-480c-8d9c-0d9901deb67c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Medical Plan'])[2]/following::a[1]</value>
      <webElementGuid>7db017c2-f8ae-453d-8525-bfb3286f3e3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diagnosis'])[1]/following::a[2]</value>
      <webElementGuid>3393ca65-14f4-4652-8e30-f4175361597c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prescription'])[1]/preceding::a[1]</value>
      <webElementGuid>498aa52c-7931-45c6-a284-8eae6f216f89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[3]/a</value>
      <webElementGuid>cca42b31-1019-4cb7-be24-41d61a39d087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'pr_id_158_header_2' and (text() = 'Foto &amp; Document' or . = 'Foto &amp; Document')]</value>
      <webElementGuid>ed648b9a-d3ac-472e-af61-68e6d8b412c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
