<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_foto_document</name>
   <tag></tag>
   <elementGuidId>7f98352b-edf6-4d6e-9476-58e55426017c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pr_id_139_header_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='pr_id_139_header_2']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@role = 'tab' and (text() = 'Foto &amp; Document' or . = 'Foto &amp; Document')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>36a07476-0e40-4887-b996-03faffa436c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>2ffbc2c5-325f-4e9e-a649-db27ba8a720e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-tabview-nav-link</value>
      <webElementGuid>5343c8a9-9a3f-4115-a40c-e91ef84cfc23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pr_id_139_header_2</value>
      <webElementGuid>c37e4cb4-b274-4f31-bb0b-0957f75b50aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>pr_id_139_content_2</value>
      <webElementGuid>0d829239-51d6-460d-98a9-1aa5f75adf65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>51e0cfce-4080-4aad-8431-7198a38ac163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d99f7c54-c81b-425f-8905-9637c069d22b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Foto &amp; Document</value>
      <webElementGuid>f0217600-cde8-4999-8be5-88ba65d7ec49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_139_header_2&quot;)</value>
      <webElementGuid>cce113c7-22da-4da1-beee-73d1b7a12bc5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='pr_id_139_header_2']</value>
      <webElementGuid>455ae492-e138-4170-8f58-aaa5f9185c24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_139']/ul/li[3]/a</value>
      <webElementGuid>91bb8ca2-ac4c-4618-a2a2-18b91cd5a374</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Item Used'])[1]/following::a[1]</value>
      <webElementGuid>52762f50-e668-428f-8af0-2ee69e454940</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Treatment Log Book'])[1]/following::a[2]</value>
      <webElementGuid>8769e02e-94e6-4220-9ed6-cb6373abd079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[2]/preceding::a[1]</value>
      <webElementGuid>c2eb546c-2fe5-43b2-aeb4-0ccf83a65980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[3]/a</value>
      <webElementGuid>664515dc-44e1-4436-b350-7276dbdcb959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'pr_id_139_header_2' and (text() = 'Foto &amp; Document' or . = 'Foto &amp; Document')]</value>
      <webElementGuid>c170f7b9-6099-4675-912b-db19b634e908</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
