<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_upload_all</name>
   <tag></tag>
   <elementGuidId>b1f7ea4b-72a5-459e-b2f2-3e61bdf09dd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#upload-multifile</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='upload-multifile']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[@type = 'button' and @id = 'upload-multifile' and (text() = 'Upload All' or . = 'Upload All')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1aaa5903-18c3-4273-9723-a9f7c703208a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Upload All</value>
      <webElementGuid>ec79dd11-059b-46bb-85b1-8f1e1a0325bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>71e33aaf-7c32-4e9f-bab8-09b12d78392b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-button p-component bg-border-netral p-button-success ml-auto</value>
      <webElementGuid>8ffb126f-958d-43e9-82c6-5fc8cd7b7f35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>upload-multifile</value>
      <webElementGuid>8dd0ce26-4322-404d-810d-8ad640ab935a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Upload All</value>
      <webElementGuid>5edb1874-1293-4d03-83cb-2dda5860cc9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;upload-multifile&quot;)</value>
      <webElementGuid>66eab4b9-ac51-40b7-835a-9a024b657f55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='upload-multifile']</value>
      <webElementGuid>dcdb92f5-e7b2-4046-a8aa-8fee4c6b9870</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='file-upload-multiple']/div[2]/div[3]/div/div/div/button</value>
      <webElementGuid>d3e8df5e-4c13-405e-9fa9-b3056694e215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose Files'])[2]/following::button[1]</value>
      <webElementGuid>f2f4704b-159f-4230-8a75-933ec86668da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div/div/button</value>
      <webElementGuid>f45dca01-c337-4840-bcaa-124aea570719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'upload-multifile' and (text() = 'Upload All' or . = 'Upload All')]</value>
      <webElementGuid>e136ea4e-1a32-4914-895b-08b45e5a7e81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
