<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_document_desc</name>
   <tag></tag>
   <elementGuidId>008cc374-2340-43ac-8743-f53600fd1e1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#documentDesc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='documentDesc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>b0660b9e-07a8-4b5b-9eb6-77acbfcfc4f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>cc033ad6-9e2b-4ee4-9576-f17b7f25a1d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>documentDesc</value>
      <webElementGuid>5c892566-f423-4dfe-a479-9e261a0927df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>340c4452-a322-4a52-a89f-9b9e30c29779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtextarea p-inputtext p-component p-inputtextarea-resizable input-text-area</value>
      <webElementGuid>676f7087-7314-42ea-9eff-fb512a0e5e85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Insert description</value>
      <webElementGuid>8aa86cbf-3015-41f6-958e-66404e652a7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;documentDesc&quot;)</value>
      <webElementGuid>119e2f36-8800-4442-bab9-6c812b932899</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='documentDesc']</value>
      <webElementGuid>7b9a6889-63d1-48ff-84df-a9fb00f6b4b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_139_content_2']/div/form/div[2]/div[2]/textarea</value>
      <webElementGuid>26a8fd90-7ca3-4d49-8b49-b611713e293d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/textarea</value>
      <webElementGuid>3093a445-a2d7-4e1a-8fe0-497200d00e04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'documentDesc' and @placeholder = 'Insert description']</value>
      <webElementGuid>095bd9b1-8fd4-4630-bcd5-de410f5dca71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
