<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cancel</name>
   <tag></tag>
   <elementGuidId>232f2645-1854-4d46-9e8b-186752c65969</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pr_id_328_content']/div/div[6]/div/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.p-button.p-component.an-base-button.an-base-button-danger.an-base-button-md.an-base-button-model-action.px-4.py-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>792737bd-7689-484c-b831-cdc3c1413682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>0ecd62b8-b043-4408-a330-67bf87d7c252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-button p-component an-base-button an-base-button-danger an-base-button-md an-base-button-model-action px-4 py-3</value>
      <webElementGuid>f05a7309-0104-46c7-a9e6-0cabf523123a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4bcef97c-45ba-4b24-891d-4cd0b8591d41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>373b6182-25ed-4b9d-beef-606c759f8a55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>ad87f6b7-a3df-4b7f-b5d7-91d7c20e7c61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_328_content&quot;)/div[@class=&quot;p-4 flex flex-column justify-content-between gap-4&quot;]/div[6]/div[@class=&quot;flex align-items-center justify-content-center gap-4&quot;]/div[@class=&quot;block&quot;]/button[@class=&quot;p-button p-component an-base-button an-base-button-danger an-base-button-md an-base-button-model-action px-4 py-3&quot;]</value>
      <webElementGuid>36de4f45-b255-4d3f-9855-a2f71e1a643b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_328_content']/div/div[6]/div/div/button</value>
      <webElementGuid>7fec089e-257b-46cd-95ad-b4efee01d533</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ya'])[4]/following::button[1]</value>
      <webElementGuid>5cb5c966-f5bc-42fa-a5f7-538c4be8bd31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak'])[5]/following::button[1]</value>
      <webElementGuid>6e2812d5-7b3c-4114-ad8c-9a11ed276488</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::button[1]</value>
      <webElementGuid>8f123076-ea27-45fb-bb19-3e2e34724752</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/button</value>
      <webElementGuid>d2736f42-51e6-48c8-ae16-868f0ba7bea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Cancel' or . = 'Cancel')]</value>
      <webElementGuid>aef7e4a4-fbab-49bb-8495-f860b1a09388</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
