<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save</name>
   <tag></tag>
   <elementGuidId>7570e0bd-69ac-4b3e-91d9-13fb3b5613c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[(text() = 'Save' or . = 'Save')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.p-button.p-component.an-base-button.an-base-button-primary.an-base-button-md.an-base-button-model-action.px-4.py-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pr_id_328_content']/div/div[6]/div/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>76ac49ae-f754-4ab5-b392-1d873b9e5a0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>75b2312a-631d-4854-a33e-b00bc44cf386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-button p-component an-base-button an-base-button-primary an-base-button-md an-base-button-model-action px-4 py-3</value>
      <webElementGuid>009f9f8d-9f13-46e8-a95f-f4ee77f8db3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b431b97f-aa31-4b78-9c20-a0fc748a86af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>0a398f18-0d5e-4d20-870b-8fd3f8da1588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>cf628d78-7494-40ea-b18a-90c974a1de5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_328_content&quot;)/div[@class=&quot;p-4 flex flex-column justify-content-between gap-4&quot;]/div[6]/div[@class=&quot;flex align-items-center justify-content-center gap-4&quot;]/div[@class=&quot;block&quot;]/button[@class=&quot;p-button p-component an-base-button an-base-button-primary an-base-button-md an-base-button-model-action px-4 py-3&quot;]</value>
      <webElementGuid>b1ff049e-ff84-4070-89f5-9a1387a7799f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_328_content']/div/div[6]/div/div[2]/button</value>
      <webElementGuid>ddd1ad3f-a539-4754-90c6-f6820ae4e511</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>22a81964-7f67-4bba-a4a6-5c35741099a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ya'])[4]/following::button[2]</value>
      <webElementGuid>320a11b1-f4bd-41bb-a586-f82d9eed178f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/button</value>
      <webElementGuid>0249d2c0-7d71-4743-a1ab-9c1bf88f1bd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>b17b8826-2c39-438d-a28a-9e2eacff84dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
