<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save</name>
   <tag></tag>
   <elementGuidId>b55b43c8-121d-4138-bbc0-7bcd57f06ed0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.p-button.p-component.p-button-netral.mr-0</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[@id = 'btn_saveAddress']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div/div[3]/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3b078039-ec9c-4070-bcde-b867ea171796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>4e9bca78-fda6-4c60-a527-739448f560fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-button p-component p-button-netral mr-0</value>
      <webElementGuid>fc82d170-79d6-451c-b184-b3c3829c9959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e92f5e62-fef4-45f4-83c6-816c2628c100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>219169bf-1adc-434d-af34-2a71f19d7974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>5d4c7675-a7cf-4974-a4e7-71ad0c0f127d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_10&quot;)/div[@class=&quot;p-dialog-footer&quot;]/div[@class=&quot;mr-3 flex justify-content-end&quot;]/div[@class=&quot;block undefined&quot;]/button[@class=&quot;p-button p-component p-button-netral mr-0&quot;]</value>
      <webElementGuid>0ebd837c-bd0d-4029-814f-c26ad7424f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_saveAddress</value>
      <webElementGuid>4ceeeedd-356f-4d8f-b050-0f9b375e49f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_10']/div[3]/div/div/button</value>
      <webElementGuid>e9317349-b735-447a-82d5-7db6cb0e399f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>52d8b783-6d3b-4d88-a735-2a9b1b5d4ca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please insert 1 - 15 numbers'])[1]/following::button[2]</value>
      <webElementGuid>0161a6d9-0e10-4f12-bfee-5bd8c69b5f77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/div/div/button</value>
      <webElementGuid>f28ceb08-c2c9-451e-a99d-5855e7f2b2cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>d45a06ba-599d-4c60-ab76-5fa8a78144f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
