<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Select_zipcode</name>
   <tag></tag>
   <elementGuidId>ffa33dc1-2cb6-4188-96bf-9f747b198779</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[@id = 'btn_selectZipcode']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[6]/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>205363a8-5d5c-4192-812d-979dc4823ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>58331f36-d624-482f-98d0-23c2e0c7c2b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-button p-component button-select-action</value>
      <webElementGuid>c91d8ffe-76e8-4cd7-a64c-8e361a2c1dc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f9fce589-6e9e-4504-b498-626a6dca5180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>a6d51cad-91c0-46dd-a7d6-5ecb14f2b97f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>c08de27a-7304-4831-9e14-c7a6af0520e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_12_content&quot;)/div[@class=&quot;p-datatable p-component p-datatable-responsive-scroll datatable-responsive mt-1 font-size-datatable custom-scrollbar&quot;]/div[@class=&quot;p-datatable-wrapper&quot;]/table[@class=&quot;p-datatable-table&quot;]/tbody[@class=&quot;p-datatable-tbody&quot;]/tr[1]/td[6]/div[@class=&quot;actions&quot;]/div[@class=&quot;block undefined&quot;]/button[@class=&quot;p-button p-component button-select-action&quot;]</value>
      <webElementGuid>1c9bf8c1-1ca6-49fe-a4d0-2f801199c19f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_selectZipcode</value>
      <webElementGuid>db8f5549-59b9-4633-a699-f1631ce3927b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_12_content']/div[3]/div/table/tbody/tr/td[6]/div/div/button</value>
      <webElementGuid>3e4dd134-6dab-4877-a270-8e7c18ad7eee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gambir'])[2]/following::button[1]</value>
      <webElementGuid>1af0a8cf-ccd1-4692-87bd-d89a18411d75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gambir'])[1]/following::button[1]</value>
      <webElementGuid>75b51b29-9296-4b1c-bf90-42f3e1f79585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kota Jakarta Pusat'])[2]/preceding::button[1]</value>
      <webElementGuid>085cd2ae-4483-4d4b-b9ea-77e688a32d9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/div/div/button</value>
      <webElementGuid>fc150143-60c7-4eb6-8868-91e4b38c3a0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>38155b60-fea9-400e-98e6-f9640189d44e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
