<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_search2</name>
   <tag></tag>
   <elementGuidId>3719d5ab-73cc-4788-b4d0-ba0b82443535</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='btn_search'])[3]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'btn_search']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.p-button.p-component.bg-border-blue.h-33.p-button-icon-only</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>92252bf3-7092-43ee-9332-a6893f31ac61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-button p-component bg-border-blue h-33 p-button-icon-only</value>
      <webElementGuid>1af67c0f-2de3-4912-9e62-867f5c930ef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e255f39c-bc06-4a4d-9fc1-9901a9038975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>028ce3f8-49a4-4ddc-9e0a-28258c763d4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>d778b4f1-be71-4780-a3d8-23f91570466c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_12_content&quot;)/div[@class=&quot;grid col-12 p-0&quot;]/div[@class=&quot;grid col-6 p-0 pt-2&quot;]/div[@class=&quot;p-inputgroup col-8&quot;]/button[@class=&quot;p-button p-component bg-border-blue h-33 p-button-icon-only&quot;]</value>
      <webElementGuid>d64c2318-d26e-4997-b54a-dbab4c3baf25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_search</value>
      <webElementGuid>8c5f76c0-2938-46e4-855e-7f9bd927e2f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_12_content']/div[2]/div/div[2]/button</value>
      <webElementGuid>bd6224f9-612f-46ef-900f-018d8d4213c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::button[1]</value>
      <webElementGuid>c598a37e-d98c-4dec-839e-6bc3d5467216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daerah Istimewa Aceh'])[4]/following::button[1]</value>
      <webElementGuid>a8dba1f9-5fbf-4a0e-8405-5c7caf6414bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[3]/preceding::button[1]</value>
      <webElementGuid>6241aaf5-e839-4986-baf2-10d91c2a60d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Postal Code'])[2]/preceding::button[1]</value>
      <webElementGuid>f9c95b74-d79e-4494-8d4f-1093115ae189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/button</value>
      <webElementGuid>4431d767-0137-4344-8828-74d840a18751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' ' or . = ' ')]</value>
      <webElementGuid>4fa61d8d-54b8-4ec0-b5de-2faadc4f16df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
