<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_notes</name>
   <tag></tag>
   <elementGuidId>f177a811-e047-45f1-a226-5397a76f8b0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pr_id_139_content_0']/div/form/div[2]/div[2]/textarea</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//textarea[@placeholder = 'Note']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>3cda9daf-a1c2-41f7-b84c-3f1f5a97c04e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Note</value>
      <webElementGuid>b35570ff-c0e9-40d7-88db-88b5ee82eff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtextarea p-inputtext p-component p-inputtextarea-resizable input-text-area-notes</value>
      <webElementGuid>65248137-5c75-43a1-a2ac-cadc13f50c9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>b7fa9501-a1bf-49f3-946e-6fe6133a7e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>4547f297-48bf-4c85-b153-a15ab5c50e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>77c19893-ea64-4824-9d45-1808389a9274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_139_content_0&quot;)/div[@class=&quot;p-blockui-container&quot;]/form[1]/div[@class=&quot;grid formgrid col-12 p-0&quot;]/div[@class=&quot;col-12 md:col-10&quot;]/textarea[@class=&quot;p-inputtextarea p-inputtext p-component p-inputtextarea-resizable input-text-area-notes&quot;]</value>
      <webElementGuid>7c8b40dd-6f1e-4444-887f-fa8271d14941</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_139_content_0']/div/form/div[2]/div[2]/textarea</value>
      <webElementGuid>605a15ca-0139-4c6a-bed6-2fc814891ce3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/textarea</value>
      <webElementGuid>f9607419-f9b2-4f3a-bed7-1fbca1de66d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Note']</value>
      <webElementGuid>d1bb79cd-a158-4619-9344-4f4adb90ad17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
