<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_bulk_delete</name>
   <tag></tag>
   <elementGuidId>e303b2b0-a280-4c57-b6f2-4a858d1309a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.p-button.p-component.bg-border-error.button-delete</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pr_id_84_content']/div/div/div/div/div/button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[@class = 'p-button p-component bg-border-error button-delete' and (text() = 'Bulk Delete' or . = 'Bulk Delete')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7cf6409e-d292-484e-a983-e44997883f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Bulk Delete</value>
      <webElementGuid>6286b864-8f39-46c3-8a02-f93f95752130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-button p-component bg-border-error button-delete</value>
      <webElementGuid>4a918ee6-cb76-4532-aeb5-30d434f6b9d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bulk Delete</value>
      <webElementGuid>012c3ae5-8b40-4beb-8a5c-3927d8ec36f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_84_content&quot;)/div[@class=&quot;p-fieldset-content&quot;]/div[@class=&quot;grid col-12 m-0 p-0&quot;]/div[@class=&quot;col-12 p-0 mb-4 mt-0&quot;]/div[@class=&quot;flex flex-row-reverse flex-wrap&quot;]/div[@class=&quot;flex align-items-center ml-2&quot;]/button[@class=&quot;p-button p-component bg-border-error button-delete&quot;]</value>
      <webElementGuid>ecf70027-07ee-452e-9d97-b62f115d5a18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_84_content']/div/div/div/div/div/button</value>
      <webElementGuid>25395320-166b-436c-80a9-8266c37b28e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service Activity'])[3]/following::button[1]</value>
      <webElementGuid>d5167213-cfc9-44dc-8183-4ff0ce1853c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Patient Registration (Consultation)'])[1]/following::button[1]</value>
      <webElementGuid>9e03a4b1-c871-4f6b-bcef-a3746344d99a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Service Activity'])[1]/preceding::button[1]</value>
      <webElementGuid>0469a5da-8798-4292-8702-0675b1be7e21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/fieldset/div/div/div/div/div/div/button</value>
      <webElementGuid>72956e98-84d4-4902-8209-59ccc7808e54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Bulk Delete' or . = 'Bulk Delete')]</value>
      <webElementGuid>4595194d-79a5-43eb-ba2d-c9d4221427d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
