<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save</name>
   <tag></tag>
   <elementGuidId>024a7310-b2f2-4d83-9be5-97bfd94e60fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-12.p-0.mt-5.justify-content-end.flex > button.p-button.p-component.mr-2.mb-2.justify-content-center.p-button-netral-reguler</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pr_id_15_content']/div[3]/div[3]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>996075c4-82db-4fda-bd2c-11592f029fa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-button p-component mr-2 mb-2 justify-content-center p-button-netral-reguler</value>
      <webElementGuid>96ee7b4e-7ec6-4380-a978-a5e1284ea132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>7ff18533-c7fc-445e-b4a3-9db2b8b0b283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_15_content&quot;)/div[@class=&quot;col-12 p-0 mt-4&quot;]/div[@class=&quot;col-12 p-0 mt-5 justify-content-end flex&quot;]/button[@class=&quot;p-button p-component mr-2 mb-2 justify-content-center p-button-netral-reguler&quot;]</value>
      <webElementGuid>435376ec-8ca7-48dc-ab26-cf6c687695c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_15_content']/div[3]/div[3]/button[2]</value>
      <webElementGuid>02fc43a9-6c71-4703-8654-c599894fa35e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>cdf748e5-fbb5-4087-86eb-f2c9192100e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select'])[6]/following::button[2]</value>
      <webElementGuid>a0bd3938-7c11-4f21-9b3a-1f7cfcfe54f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Post'])[1]/preceding::button[1]</value>
      <webElementGuid>15fc3280-a569-4bdb-afdd-00e0bfe268d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button[2]</value>
      <webElementGuid>15db8a5c-bb03-443b-8561-046baf337205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>c8e7301e-b5f7-498c-80c9-d81ec580a796</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
