<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_add_product</name>
   <tag></tag>
   <elementGuidId>63ea1a03-6e6c-40a8-9a0e-ef1d1509cb74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@class = 'p-button p-component button-select-action' and (text() = 'Add' or . = 'Add')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(6) > div.actions > button.p-button.p-component.button-select-action</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pr_id_22_content']/div[2]/div/div/table/tbody/tr/td[6]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>015ae2af-80d4-4b13-a364-85644415a325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-button p-component button-select-action</value>
      <webElementGuid>ca853164-9653-4b94-93b5-ccbd7c87c959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>66846a0c-ca5d-4053-b615-9ed97c9999b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_22_content&quot;)/div[@class=&quot;col-12&quot;]/div[@class=&quot;p-datatable p-component p-datatable-responsive-scroll font-size-datatable edit-inline&quot;]/div[@class=&quot;p-datatable-wrapper&quot;]/table[@class=&quot;p-datatable-table&quot;]/tbody[@class=&quot;p-datatable-tbody&quot;]/tr[1]/td[6]/div[@class=&quot;actions&quot;]/button[@class=&quot;p-button p-component button-select-action&quot;]</value>
      <webElementGuid>b8c97da2-7688-4832-a4d8-b40b9d43e374</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_22_content']/div[2]/div/div/table/tbody/tr/td[6]/div/button</value>
      <webElementGuid>7d116fee-f94f-4fd4-b837-5185850bddff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/following::button[1]</value>
      <webElementGuid>9d4afacb-4a42-49b8-931a-38f7ab0f7413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GXJG2'])[1]/following::button[1]</value>
      <webElementGuid>78a38cba-e4b6-4528-9b99-f08b83ef32e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FCBR2'])[1]/preceding::button[1]</value>
      <webElementGuid>59269ec1-6e47-419b-b5a1-4e02b942d4fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/div/button</value>
      <webElementGuid>e1aa3ffb-c92e-4689-8a3d-0f2bf3091b45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Add' or . = 'Add')]</value>
      <webElementGuid>d6c6b13e-1c61-45db-93b0-c2e9e545fdce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
