<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textbox_signa</name>
   <tag></tag>
   <elementGuidId>fb22db27-7127-4762-91df-ef22ee9f0494</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-8.py-3.px-0 > input.p-inputtext.p-component.input-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>69373c64-0622-4fb8-919b-e46bd09f0f6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please Input</value>
      <webElementGuid>e81513e7-77d2-432f-88d9-36e255f40420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component input-text</value>
      <webElementGuid>314e4487-c63d-4e80-858e-849145f07c2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_15_content&quot;)/div[@class=&quot;grid mt-2 m-0 p-0&quot;]/div[@class=&quot;col-12 md:col-6 py-0&quot;]/div[@class=&quot;grid m-0 p-0 align-items-center&quot;]/div[@class=&quot;col-8 py-3 px-0&quot;]/input[@class=&quot;p-inputtext p-component input-text&quot;]</value>
      <webElementGuid>11ad15af-24a0-4315-b739-86e26a57a3c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[4]</value>
      <webElementGuid>edf9baca-285b-4c6d-b1cf-1848d8546146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_15_content']/div[2]/div[2]/div/div[2]/input</value>
      <webElementGuid>8b7e0698-eb43-4906-94b3-a622aed414a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>b85b8bb6-f625-43c1-8e5f-144a91ccbd1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Please Input']</value>
      <webElementGuid>fcb7f478-233a-4c30-ac09-f751d318e045</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
