<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textbox_product_search</name>
   <tag></tag>
   <elementGuidId>16ea3313-8f0e-4068-a84e-f2f4be846b25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#seacrh</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='seacrh']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4c005d7c-4613-4a26-a394-59f84c55664f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component input-search</value>
      <webElementGuid>33bfdbb8-0838-4dd4-8c24-eaefb25bef76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>04e2efa0-5c44-43a3-82b3-22065d2d1d79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>seacrh</value>
      <webElementGuid>81e17418-c315-4bda-b11e-bbe6718b80a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;seacrh&quot;)</value>
      <webElementGuid>25183300-beca-4b59-9db0-3efbc6929667</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='seacrh']</value>
      <webElementGuid>a3e9f7c5-b09c-42e3-b258-5dc01dbe2a21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_22_content']/div/div[2]/div/input</value>
      <webElementGuid>1a1c9b88-bc71-4ac5-b364-90bef271fd68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/input</value>
      <webElementGuid>d07b8e1b-aea3-4bd0-9a3a-5cad18d53b69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Search' and @id = 'seacrh']</value>
      <webElementGuid>2fc4cd09-1502-40d5-80b2-ad2ae5df3f2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
