<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>validation_phone</name>
   <tag></tag>
   <elementGuidId>7ed3e094-ac4e-43f1-850f-99ffffd4b72b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.validation.text-right</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Please insert 1 - 12 numbers' or . = 'Please insert 1 - 12 numbers')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div[2]/div/form/div[5]/div[2]/div/div[7]/div[2]/div/div/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7f721a41-4c56-46bf-b290-84e07127adfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validation text-right</value>
      <webElementGuid>ab4b32c4-377a-4a20-b0fb-e8561b8d9f37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please insert 1 - 12 numbers</value>
      <webElementGuid>70cde09c-8a3c-4215-8008-5e1d77466615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;layout-wrapper layout-static p-ripple-disabled layout-sidebar-darkgray&quot;]/div[@class=&quot;layout-content-wrapper&quot;]/div[@class=&quot;layout-content padding-out-content&quot;]/div[@class=&quot;p-blockui-container&quot;]/div[@class=&quot;col-12 xl:col-12 p-0 mb-8rem&quot;]/form[1]/div[@class=&quot;grid m-0 p-0&quot;]/div[@class=&quot;col-12 md:col-6 py-1 px-0 md:pl-3 md:py-0&quot;]/div[@class=&quot;p-3 border-box h-full&quot;]/div[@class=&quot;flex&quot;]/div[@class=&quot;flex-grow-1 flex align-items-center justify-content-start&quot;]/div[@class=&quot;flex flex-row flex-wrap justify-content-end card-container blue-container&quot;]/div[@class=&quot;grid-container ml-3&quot;]/span[@class=&quot;validation text-right&quot;]</value>
      <webElementGuid>1873b438-23fa-4993-ba30-da630709e65b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]/div/form/div[5]/div[2]/div/div[7]/div[2]/div/div/span[2]</value>
      <webElementGuid>16814639-8752-45b0-89e7-d6f77e517ffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/following::span[3]</value>
      <webElementGuid>db9dab71-8bce-4e79-aeeb-f20777de0272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[9]/preceding::span[1]</value>
      <webElementGuid>c1b837ea-e69c-4c5d-8876-3bad564b3557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Please insert 1 - 12 numbers']/parent::*</value>
      <webElementGuid>e09665b1-c077-4f42-92e5-f2a4e852892b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span[2]</value>
      <webElementGuid>dfa2c0ed-4996-4df8-ba29-d4fad623e841</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Please insert 1 - 12 numbers' or . = 'Please insert 1 - 12 numbers')]</value>
      <webElementGuid>d7e47de4-b86d-4503-bb65-6ac284ab350f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
