<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_search</name>
   <tag></tag>
   <elementGuidId>e6da76b3-a5b9-4632-89a0-d9ebaa1e3a9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='btn_search'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.block.undefined > #btn_search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a40fd3bc-67f9-4f7e-9800-fcfaab2fc339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-button p-component p-button-default bg-border-blue p-button-icon-only</value>
      <webElementGuid>a3f27acc-3ba0-42c5-a84e-02b03610f015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_search</value>
      <webElementGuid>3dcd3658-1497-4917-ab3b-227b31692fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>028b17eb-4dda-4e49-9896-1fc337fe5324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bd023861-0391-4460-96e6-c9d54b4b872e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>367097b1-e9e9-4ed6-9c63-1627c61825ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>d1ab06a1-dd13-43a3-bd63-c57254930727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_10_content&quot;)/div[@class=&quot;col-12 p-0 my-2&quot;]/div[@class=&quot;flex flex-row flex-wrap justify-content-center&quot;]/div[@class=&quot;grid col-12 align-items-center p-0 m-0&quot;]/div[@class=&quot;col-8 p-0&quot;]/div[@class=&quot;grid row-gap-3 col-12 p-0 justify-content-between m-0&quot;]/div[@class=&quot;col-12 align-items-center text-value border-round p-0&quot;]/div[@class=&quot;p-inputgroup h-33&quot;]/div[@class=&quot;block undefined&quot;]/button[@id=&quot;btn_search&quot;]</value>
      <webElementGuid>1ff805da-78b3-443e-a36c-14e650778c27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='btn_search'])[2]</value>
      <webElementGuid>ce485b0e-4ffa-4fc5-b5ca-8bf6b645a707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_10_content']/div[14]/div/div/div[2]/div/div/div/div/button</value>
      <webElementGuid>cc79e90f-1f8b-4862-a82d-c6cb4bfec115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[23]/following::button[1]</value>
      <webElementGuid>e7aa5bd4-015b-4bf7-86ab-7a56517d0996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[24]/preceding::button[1]</value>
      <webElementGuid>c478b6c6-0505-4052-8559-94687bdf4e46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div/div[2]/div/div/div/div/button</value>
      <webElementGuid>af983257-52a3-4414-aefb-6754823cb4c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn_search' and @type = 'button' and (text() = ' ' or . = ' ')]</value>
      <webElementGuid>7a4b6aa8-9867-4c2f-a038-c61ede08a6a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
