<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Select</name>
   <tag></tag>
   <elementGuidId>d4ecf9dd-669b-49a7-9464-7b3477a8ee90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id = 'btn_selectZipcode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn_selectZipcode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn_selectZipcode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c3392e0a-de28-4bf1-9278-8fc044f408df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>88cb482c-f9a6-4b12-9e82-4fe6ea908399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-button p-component button-select-action</value>
      <webElementGuid>804a6a1b-79ab-4f0d-bb68-d3276741da72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_selectGuarantor</value>
      <webElementGuid>edd69434-8c69-4080-a684-fd963687e0af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fe758ae5-7a3b-46b0-a6b6-bfdf783ba8f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>e9f81b94-0568-4350-9f2f-8cbb771bf32b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>315e19ab-1d71-4a89-b107-f3c416ffccfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_14_content&quot;)/div[@class=&quot;p-datatable p-component p-datatable-responsive-scroll datatable-responsive mt-1 font-size-datatable custom-scrollbar&quot;]/div[@class=&quot;p-datatable-wrapper&quot;]/table[@class=&quot;p-datatable-table&quot;]/tbody[@class=&quot;p-datatable-tbody&quot;]/tr[1]/td[6]/div[@class=&quot;actions&quot;]/div[@class=&quot;block undefined&quot;]/button[@id=&quot;btn_selectZipcode&quot;]</value>
      <webElementGuid>84362571-7da7-4854-829f-c17f7d534960</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn_selectZipcode']</value>
      <webElementGuid>3a7ccf8c-0604-401d-92f0-7cd51540794c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_14_content']/div[3]/div/table/tbody/tr/td[6]/div/div/button</value>
      <webElementGuid>f4d9ac43-8557-4f7f-9191-5b268c55a90a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pulau Maria'])[1]/following::button[1]</value>
      <webElementGuid>3f700cc0-8c64-4f50-b84c-88a7583afc96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Teluk Dalam'])[1]/following::button[1]</value>
      <webElementGuid>5c0991cb-6814-4a05-bb72-e4be1abc9893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kab. Simeulue'])[2]/preceding::button[1]</value>
      <webElementGuid>5cc56b3b-36cd-4c12-901b-fc370a046376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/div/div/button</value>
      <webElementGuid>09263fad-ea9a-4b97-b534-4e08d575d7ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn_selectZipcode' and (text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>5ce07caf-4bbe-4b4b-abbf-72cf562bf796</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
