<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Select_zipcode</name>
   <tag></tag>
   <elementGuidId>7fd70807-db65-49e8-9aaf-154cf46e5698</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id = 'btn_selectZipcode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn_selectZipcode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn_selectZipcode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d1572de3-04dc-4227-9523-9f931ff49800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>ac7a74fd-ceb5-49e1-b8d5-6d6f6ba25efc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-button p-component button-select-action</value>
      <webElementGuid>d6c70b73-1702-4539-97b5-d3ea79036f52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_selectZipcode</value>
      <webElementGuid>1f6bd4f1-a73f-4517-bafb-2e8bf60d4275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d04e6caa-ef41-4254-ae71-2892a8358b53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>5cf18b8f-bb2b-471d-8a9f-c93a398d4e93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>b1de6a83-213e-47fe-8022-8ed2c1aa30cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_14_content&quot;)/div[@class=&quot;p-datatable p-component p-datatable-responsive-scroll datatable-responsive mt-1 font-size-datatable custom-scrollbar&quot;]/div[@class=&quot;p-datatable-wrapper&quot;]/table[@class=&quot;p-datatable-table&quot;]/tbody[@class=&quot;p-datatable-tbody&quot;]/tr[1]/td[6]/div[@class=&quot;actions&quot;]/div[@class=&quot;block undefined&quot;]/button[@id=&quot;btn_selectZipcode&quot;]</value>
      <webElementGuid>eee3a4ca-92ad-44d4-aa65-4c22955d4f9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn_selectZipcode']</value>
      <webElementGuid>9e52838e-958e-4ffd-a112-d44ad8817185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_14_content']/div[3]/div/table/tbody/tr/td[6]/div/div/button</value>
      <webElementGuid>2cad3ee3-69a3-49e9-96c0-33dd16c08175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pulau Maria'])[1]/following::button[1]</value>
      <webElementGuid>71e65115-c5d2-4cda-9f2e-841e1cb2bf49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Teluk Dalam'])[1]/following::button[1]</value>
      <webElementGuid>0ab20705-8023-4a9a-b9ca-f9200edf4532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kab. Simeulue'])[2]/preceding::button[1]</value>
      <webElementGuid>37c7a9d2-f8fc-46bb-81ed-bde62755b8c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/div/div/button</value>
      <webElementGuid>b51f429f-1392-44a8-bd80-8b5387afbc54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn_selectZipcode' and (text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>1c7edbbb-0910-4c1a-9d70-f7af244ef308</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
