<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_registration_info</name>
   <tag></tag>
   <elementGuidId>6e47163c-9630-4f1d-8058-64b71db1875a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pr_id_61_header</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='pr_id_61_header']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[(text() = 'Registration Info' or . = 'Registration Info')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3c93dd3d-89d8-4f4f-9300-467ace8036ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#pr_id_61_content</value>
      <webElementGuid>772300d4-eb15-44ae-aee4-e7b15d01e046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>pr_id_61_content</value>
      <webElementGuid>01656326-2b52-44c1-b68d-1a20789e133c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pr_id_61_header</value>
      <webElementGuid>53b98327-a8f7-411b-bb51-d5501814ee6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7519f286-1411-4af1-b879-6174bcf4b1a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Registration Info</value>
      <webElementGuid>f4a81aa6-55e7-4cda-ac75-7262c301fff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_61_header&quot;)</value>
      <webElementGuid>c7d5204f-6828-4987-ac49-96da21319a98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='pr_id_61_header']</value>
      <webElementGuid>d5868847-72a4-4e1c-9c02-bd59ba5cef76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='pr_id_61']/legend/a</value>
      <webElementGuid>6361082f-3ab4-4a9d-9eb7-a36165b09971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::a[1]</value>
      <webElementGuid>e3214d35-23f7-422b-993b-946244b1c6c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preference Note'])[1]/following::a[1]</value>
      <webElementGuid>d4335410-385f-4498-b878-6eb9d9fc2dea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Appointment No'])[1]/preceding::a[1]</value>
      <webElementGuid>7a1753e1-66df-4b92-85be-82c53f2b8bcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#pr_id_61_content')]</value>
      <webElementGuid>132bbda7-a8e4-4117-a899-23b51854b2c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/legend/a</value>
      <webElementGuid>9e66bd2d-7bbe-4c28-b4da-523e9bb61530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#pr_id_61_content' and @id = 'pr_id_61_header' and (text() = 'Registration Info' or . = 'Registration Info')]</value>
      <webElementGuid>aecde51e-4881-4ffb-ad54-373fb78b361f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
