<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_service_activity_information</name>
   <tag></tag>
   <elementGuidId>0a7df77d-b51f-4bf3-aee9-c2710f3c6f66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pr_id_137_header</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='pr_id_137_header']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[(text() = 'Service Activity Information' or . = 'Service Activity Information')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7dd45566-36af-4113-9818-b6a9264d9da0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#pr_id_137_content</value>
      <webElementGuid>2735c4c6-cd1f-46de-a82a-09f7debdca9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>pr_id_137_content</value>
      <webElementGuid>1f0bc129-cdfe-4080-81c6-903fe86398d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pr_id_137_header</value>
      <webElementGuid>8cdc3912-e2b2-4777-ab93-6344664c30e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>056f21f7-5829-49fa-a66c-2ec5dedd5a2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Service Activity Information</value>
      <webElementGuid>b9bca811-e9cb-44c4-8dfb-cd805a310fa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_137_header&quot;)</value>
      <webElementGuid>5db0e222-0544-4297-b56d-984997c12948</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='pr_id_137_header']</value>
      <webElementGuid>1ca326f4-2dd5-4000-9559-09a722eb1c3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='pr_id_137']/legend/a</value>
      <webElementGuid>39d09512-ca04-42dd-83fe-ae725b661ceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Age'])[1]/following::a[1]</value>
      <webElementGuid>b9d44e6b-7d7e-4054-93d6-96b8e68ab34b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::a[1]</value>
      <webElementGuid>1a0df97f-8ad0-4fa0-9165-36fc4959c284</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='process'])[1]/preceding::a[1]</value>
      <webElementGuid>3d2f90ed-0125-46ce-aac3-6ec49fe53bde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#pr_id_137_content')]</value>
      <webElementGuid>a5696906-39e5-46d2-8292-583e3db20034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/fieldset/legend/a</value>
      <webElementGuid>1243d6fe-17d5-486b-9ca1-70bb4f489489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#pr_id_137_content' and @id = 'pr_id_137_header' and (text() = 'Service Activity Information' or . = 'Service Activity Information')]</value>
      <webElementGuid>c0b3a04a-b387-44d5-b50b-1541c1120a87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
