<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_service_activity_detail</name>
   <tag></tag>
   <elementGuidId>64fe6416-dbb7-4f39-88f0-1851fb09ae9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#service-activity-detail-fieldset_header</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='service-activity-detail-fieldset_header']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@href = '#service-activity-detail-fieldset_content' and @id = 'service-activity-detail-fieldset_header' and (text() = 'Service Activity Detail' or . = 'Service Activity Detail')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>20b1cb00-8b11-44f2-8f78-232af3b7dcbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#service-activity-detail-fieldset_content</value>
      <webElementGuid>3937c9fb-9961-4cbd-8e8d-7f8295837f0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>service-activity-detail-fieldset_content</value>
      <webElementGuid>733de628-8c32-4ca4-bd62-f616f446287b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>service-activity-detail-fieldset_header</value>
      <webElementGuid>85d35d4f-e9c7-4853-b5ce-72764486d315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a02e6e55-48c5-43b7-b342-4314ca12ebb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Service Activity Detail</value>
      <webElementGuid>d85640bb-f4e7-4edf-bf18-9b3463e43dd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;service-activity-detail-fieldset_header&quot;)</value>
      <webElementGuid>392f4bda-4c7d-425f-93cf-79c16e14a122</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='service-activity-detail-fieldset_header']</value>
      <webElementGuid>88698a2b-c8af-4fa2-afe0-6f431004b5fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='service-activity-detail-fieldset']/legend/a</value>
      <webElementGuid>abf03e09-5b0e-4339-b3c7-538fdde29c80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Week'])[1]/following::a[1]</value>
      <webElementGuid>bd9e806e-7eaa-499e-9d7a-14ba41bf125f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::a[1]</value>
      <webElementGuid>ed3220dc-8bb1-4693-8a63-414e4665f6c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[2]/preceding::a[1]</value>
      <webElementGuid>21e5e435-587f-45bd-88e9-811c9544ed7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#service-activity-detail-fieldset_content')]</value>
      <webElementGuid>a40f0858-1070-4274-aade-965072c7d30b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/legend/a</value>
      <webElementGuid>d0abcd41-a5e8-49e0-b760-1c16ea11eb86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#service-activity-detail-fieldset_content' and @id = 'service-activity-detail-fieldset_header' and (text() = 'Service Activity Detail' or . = 'Service Activity Detail')]</value>
      <webElementGuid>54213cd4-a65c-4785-aaa2-a14019d063f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
