<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_process</name>
   <tag></tag>
   <elementGuidId>29e38f08-85f9-4002-a9b7-333aa38ed7d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.p-button.p-component.bg-border-netral.button-add</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3f79184e-f4a1-4fbb-98dc-f3f31c7572d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>process</value>
      <webElementGuid>a529f8ac-c938-48b5-adaf-4d174651118c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-button p-component bg-border-netral button-add</value>
      <webElementGuid>d0d419ee-133a-4698-9f19-924f924db174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>116a8d60-cc2a-48c1-9658-2e9af975eb8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>process</value>
      <webElementGuid>dd537705-315e-4b36-ad57-28664d48872f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_137_content&quot;)/div[@class=&quot;p-fieldset-content&quot;]/div[@class=&quot;flex flex-column md:flex-row md:justify-content-end md:align-items-center mb-2&quot;]/div[@class=&quot;grid formgrid&quot;]/div[@class=&quot;col-12 mb-2 lg:col-5 lg:mb-0&quot;]/button[@class=&quot;p-button p-component bg-border-netral button-add&quot;]</value>
      <webElementGuid>912104e1-c583-454f-9b34-a63de86c05aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>ccd9ea64-38e6-497e-ba38-fd8fa4b0e761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_137_content']/div/div/div/div/button</value>
      <webElementGuid>e140d819-545f-4af4-b638-562ef0dc9504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service Activity Information'])[1]/following::button[1]</value>
      <webElementGuid>4bda56e4-069f-416e-a279-60639857a33a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Age'])[1]/following::button[1]</value>
      <webElementGuid>335dbb22-9623-4ae3-8551-f618d34c145d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Referral ID / By'])[1]/preceding::button[1]</value>
      <webElementGuid>2692df13-5182-460d-89ef-afb17ea66a22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div/div/div/div/button</value>
      <webElementGuid>7dcbb6c8-0513-4169-bb79-74f8165a7de4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'process' or . = 'process')]</value>
      <webElementGuid>2a300aa3-e212-4bb0-a7d6-c8883ad82bab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
