<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textbox_next_schedule</name>
   <tag></tag>
   <elementGuidId>b7d92660-eb6f-4a49-b189-4068a30a3e18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#next_schedule</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='next_schedule']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f208840e-d4be-4614-887b-5ba3b5e51602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component input-text text-right</value>
      <webElementGuid>a576f2a5-b3ef-4fc3-b823-92f014c5b1c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0c22fa59-c8db-432d-92f3-3c400f8efab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>e404637a-bafb-4d45-9ffc-791ac9b45e17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>next_schedule</value>
      <webElementGuid>e27d1457-11a2-45cd-a43f-d1db63dd222a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;next_schedule&quot;)</value>
      <webElementGuid>c521af04-7e19-4503-b0a3-acb2adbeed7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='next_schedule']</value>
      <webElementGuid>a6df6de2-ee8b-413f-a868-23cc3c278295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_137_content']/div/div[2]/div[2]/div[5]/div[2]/input</value>
      <webElementGuid>5c7e2894-be2c-46af-8db1-85ba58682ae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/input</value>
      <webElementGuid>f0ec881f-2c83-4b19-a673-7a9013a1270f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'next_schedule']</value>
      <webElementGuid>f10e808e-e0e2-4717-9a51-bd9bc43d7c9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
