<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Konsultasi 1 - Bed 2  141500 - 143000 (1)</name>
   <tag></tag>
   <elementGuidId>6765b15a-2343-45a2-8d01-4f7c7addef24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.p-dropdown-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::li[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>63c5e756-55ee-45d9-81e1-38235d4fc7ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-dropdown-item</value>
      <webElementGuid>a169112e-ab55-48f2-87f1-74b968bd0d36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Konsultasi 1 - Bed 2 : 14:15:00 - 14:30:00</value>
      <webElementGuid>0e2835c0-61df-4772-93cc-19f1663b28ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>5dcbbb2b-1884-4ced-8a00-1165834f4589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5c4de8b5-a265-405a-9db9-66881cccba9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Konsultasi 1 - Bed 2 : 14:15:00 - 14:30:00</value>
      <webElementGuid>c129e5fa-a95f-4717-8e6a-b8efe0e5a198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;p-dropdown-panel p-component p-connected-overlay-enter-done&quot;]/div[@class=&quot;p-dropdown-items-wrapper&quot;]/ul[@class=&quot;p-dropdown-items&quot;]/li[@class=&quot;p-dropdown-item&quot;]</value>
      <webElementGuid>0ad968cc-500d-41c8-b71c-5b5ec09ed1a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::li[1]</value>
      <webElementGuid>e21740d6-0d00-4d56-afd1-c991dcc3e60d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[2]/following::li[1]</value>
      <webElementGuid>9e8ec6e6-c6ee-4f72-9359-bc4cf77be085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Konsultasi 1 - Bed 2 : 14:30:00 - 14:45:00'])[1]/preceding::li[1]</value>
      <webElementGuid>8b8eb07a-593e-4bf5-8537-58da2be6dc1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Konsultasi 1 - Bed 2 : 14:45:00 - 15:00:00'])[1]/preceding::li[2]</value>
      <webElementGuid>ad0ac20f-a4f5-4b6b-afee-e35c770559d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Konsultasi 1 - Bed 2 : 14:15:00 - 14:30:00']/parent::*</value>
      <webElementGuid>e0bd41f1-d697-4d2c-81ca-3ef508aa8b82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/ul/li</value>
      <webElementGuid>892a0eaf-b3c9-44c3-83ec-f735a3888f5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Konsultasi 1 - Bed 2 : 14:15:00 - 14:30:00' or . = 'Konsultasi 1 - Bed 2 : 14:15:00 - 14:30:00')]</value>
      <webElementGuid>9ac66a04-cad8-4daf-bc97-18efa97ee314</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
