<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_add</name>
   <tag></tag>
   <elementGuidId>aee619ed-ce4e-4109-8317-ae074e4ee753</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@class = 'p-button p-component justify-content-center button-action-add mr-2' and (text() = 'Add' or . = 'Add')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div[2]/div[4]/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.p-button.p-component.justify-content-center.button-action-add.mr-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>069a2f54-b8d1-455b-88ee-b4e229aeec4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-button p-component justify-content-center button-action-add mr-2</value>
      <webElementGuid>06bf83d7-4245-407c-8ebe-dd7dcc60fa9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>d3494c6f-9dc0-4afa-b574-e394477b19e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;layout-wrapper layout-static p-ripple-disabled layout-sidebar-darkgray&quot;]/div[@class=&quot;layout-content-wrapper&quot;]/div[@class=&quot;layout-content padding-out-content&quot;]/div[@class=&quot;p-blockui-container&quot;]/div[@class=&quot;card border-box&quot;]/div[@class=&quot;col-12 grid justify-content-end my-3 p-0&quot;]/button[@class=&quot;p-button p-component justify-content-center button-action-add mr-2&quot;]</value>
      <webElementGuid>7e958914-ab8d-422b-9c40-a5f540e1451e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]/div[4]/div[2]/button</value>
      <webElementGuid>2fba1203-597b-488b-ba5e-16b5e6891f7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 1 of 1'])[1]/following::button[6]</value>
      <webElementGuid>e38e8811-c54c-444b-b25e-1d3e67ea73ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Botol'])[1]/following::button[6]</value>
      <webElementGuid>6b4a5c88-a1b8-43ed-95bf-385043c93eb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/preceding::button[1]</value>
      <webElementGuid>9d958cfa-970f-47de-b67e-8d21e7291212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>c0bedf4f-9eed-4bd3-ab79-fbda0d00846d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Add' or . = 'Add')]</value>
      <webElementGuid>cfed1059-42b9-4d21-8e18-fdde70a241e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
