<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cancel</name>
   <tag></tag>
   <elementGuidId>782a0282-ac13-474f-b48b-8b94cb6e69cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.flex > button.p-button.p-component.button-select-action.button-netral.mr-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pr_id_20_content_3']/div/div[2]/div/div/table/tbody/tr/td[8]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>59ce32e7-84db-428a-ad4d-d190f46da2c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>09dd0de1-ec6f-49db-9543-b8d894274331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-button p-component button-select-action button-netral mr-2</value>
      <webElementGuid>44f26395-1cc6-4e18-91b8-1d4ccdcc456d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>10fe4db7-f2a3-4297-9b1d-18f04b7884f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>6172ab4d-b662-463d-820c-99cd7a176a15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>dac73e8a-846a-4b0e-8a1e-d475b30309b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_20_content_3&quot;)/div[@class=&quot;grid col-12 m-0 p-1&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;p-datatable p-component p-datatable-responsive-scroll font-size-datatable edit-inline&quot;]/div[@class=&quot;p-datatable-wrapper&quot;]/table[@class=&quot;p-datatable-table&quot;]/tbody[@class=&quot;p-datatable-tbody&quot;]/tr[1]/td[8]/div[@class=&quot;flex&quot;]/button[@class=&quot;p-button p-component button-select-action button-netral mr-2&quot;]</value>
      <webElementGuid>001e2f51-17d9-4388-9e73-a923df136be2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_20_content_3']/div/div[2]/div/div/table/tbody/tr/td[8]/div/button</value>
      <webElementGuid>10d4d548-882f-49b8-a972-a6fb24dbb20b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[2]/following::button[1]</value>
      <webElementGuid>5b675009-23a3-4ce2-90f4-dd52f6c2e0fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diskon Direksi Arya Noble'])[2]/following::button[2]</value>
      <webElementGuid>86633918-6706-4de1-a1af-b4d615fb333e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Klinik Utama Erha Ultimate BSD'])[1]/preceding::button[2]</value>
      <webElementGuid>be051010-f75f-46bf-8feb-b10fb25cee5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/div/button</value>
      <webElementGuid>e4b2b48f-7ed1-4e6d-927f-e2c55a1ad18c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Cancel' or . = 'Cancel')]</value>
      <webElementGuid>bbbab046-f8a7-4c59-a2af-447bb3501182</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
