<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cancel Request</name>
   <tag></tag>
   <elementGuidId>b10f0d30-6647-4017-80aa-56b236023f63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_cancelRequest</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn_cancelRequest']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>801ede2b-dbfb-4ce4-9db7-d5d17e90f3f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Cancel Request</value>
      <webElementGuid>b8c9380b-ef90-472f-a20b-d08f3fd2ac39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-button p-component button-select-danger mr-2 w-full</value>
      <webElementGuid>dcb55b3e-e38d-426c-80a1-142b082ae1ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_cancelRequest</value>
      <webElementGuid>738b1394-8e44-4e8b-a357-15f29e82b384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>41584f0d-8ea4-40d9-91c2-4f1c4d75a7c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>06dd4a2b-ea08-4c5f-b428-5dfb52aa002e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel Request</value>
      <webElementGuid>e72ad748-27d9-40f3-b83f-4411672508c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_cancelRequest&quot;)</value>
      <webElementGuid>70c45cb4-84ed-468f-b787-a57ea79b1eee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn_cancelRequest']</value>
      <webElementGuid>a390fb2e-418e-4795-923c-039df25664a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_20_content_3']/div/div[2]/div/div/table/tbody/tr/td[8]/div/div/button</value>
      <webElementGuid>1016412e-ac31-479d-af78-a9667661577d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Waiting Add Approval'])[1]/following::button[1]</value>
      <webElementGuid>f16326ea-cebc-45f6-9d87-f2350bd9bac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[2]/following::button[1]</value>
      <webElementGuid>144490f7-6fdb-4f6f-ba10-9c49c87bbe65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[1]/preceding::button[1]</value>
      <webElementGuid>ef564b55-3c44-4579-bb0f-5ed543d8d5fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/div/div/button</value>
      <webElementGuid>4cd405b4-94a5-4da9-98ff-3a3355d7deb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn_cancelRequest' and (text() = 'Cancel Request' or . = 'Cancel Request')]</value>
      <webElementGuid>cdb3541d-1e01-49d4-98fe-e05696ebad5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
