<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_search</name>
   <tag></tag>
   <elementGuidId>3d05736a-bc18-4c5f-8f36-b931f26afe69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.p-dropdown-filter.p-inputtext.p-component</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d1809a71-c8f1-4a21-a1e5-426bc2f5306a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cf96fb89-0240-4418-b005-95618250175a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3b448852-ade2-4b5c-9bdd-fb7b427adcca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-dropdown-filter p-inputtext p-component</value>
      <webElementGuid>1f03be1e-4cdb-499e-beb4-a431284bd8ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>filterinput</value>
      <webElementGuid>d96efb1d-4b50-4e22-a010-b034c3e0877c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;p-dropdown-panel p-component p-ripple-disabled p-connected-overlay-enter-done&quot;]/div[@class=&quot;p-dropdown-header&quot;]/div[@class=&quot;p-dropdown-filter-container&quot;]/input[@class=&quot;p-dropdown-filter p-inputtext p-component&quot;]</value>
      <webElementGuid>743d02eb-3b11-4e07-9a74-9c5cdb19dd1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[4]</value>
      <webElementGuid>4497cd20-9f20-4d5d-a9a7-e7a007ae05e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/div[3]/div/div/input</value>
      <webElementGuid>f2a3f918-abc3-4ddd-a711-c4f1366fb1a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>178dc9e4-e604-4099-8673-4a08f7a2522c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
