<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_membership</name>
   <tag></tag>
   <elementGuidId>b8b4a736-81c4-440f-9a89-298164917559</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#membership_id > span.p-dropdown-label.p-inputtext.p-placeholder</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='membership_id']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8cef54f6-518d-4605-8621-d0ab9cf31d4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-dropdown-label p-inputtext p-placeholder</value>
      <webElementGuid>4b6f4f78-1e7e-4993-bf37-b6412281a76c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>33ce027c-e2fa-4cd8-8311-6d9bf8478b12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please Select</value>
      <webElementGuid>9e94eb82-6cb1-47fb-a9ca-67ad8f4489fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;membership_id&quot;)/span[@class=&quot;p-dropdown-label p-inputtext p-placeholder&quot;]</value>
      <webElementGuid>85a57931-c333-42ed-856f-57cbbbf71f6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='membership_id']/span</value>
      <webElementGuid>3fddce5c-a7bd-4c79-a6a5-4876f0632d18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[1]/following::span[1]</value>
      <webElementGuid>f9742192-7615-494d-a3b7-5f54d8fc4ac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status Approval'])[1]/following::span[2]</value>
      <webElementGuid>8bca5779-68c2-4055-b8b0-e08d43de9037</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[2]/preceding::span[1]</value>
      <webElementGuid>79ea2fd3-2ad0-4589-b219-82aa0b235789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::span[2]</value>
      <webElementGuid>dff2798f-173c-48d2-b186-39adf88b3315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/span</value>
      <webElementGuid>8329fc6b-49cc-43ca-a0b3-2c349e267c51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Please Select' or . = 'Please Select')]</value>
      <webElementGuid>c16f27a4-a534-441f-ab55-e0aca0c960e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
