<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Medical Plan</name>
   <tag></tag>
   <elementGuidId>43e95e3f-e6d2-42ef-ad3a-a7b71ff3bbeb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pr_id_202_header_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='pr_id_202_header_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6f545fee-73a8-4c0d-9402-14fee5325870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>ec335d12-cfbe-47a6-8035-b500f7d07bd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-tabview-nav-link</value>
      <webElementGuid>1a480428-ca46-4a07-acf7-8a8f1dc1b275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pr_id_202_header_1</value>
      <webElementGuid>aa33840f-38cb-43af-9726-5a492fc55b61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>pr_id_202_content_1</value>
      <webElementGuid>d314cf47-3762-4b72-bae0-96ee9cba08ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6ae89876-a3d3-44bb-9c6f-d6d75dcfc45a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>dfd2781f-2058-4300-9c5f-bd9ab344dd85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Medical Plan</value>
      <webElementGuid>2f623940-143c-43f9-9b3a-bbc6dcc57f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_202_header_1&quot;)</value>
      <webElementGuid>b983d58e-697a-4e7e-b412-b6ee80033843</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='pr_id_202_header_1']</value>
      <webElementGuid>0b5e21f0-0b05-4d27-aae3-d374ec276040</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_202']/ul/li[2]/a</value>
      <webElementGuid>c53b580a-57b9-4d02-a0cd-8efabdd7caaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diagnosis'])[1]/following::a[1]</value>
      <webElementGuid>8a0b2266-6db0-4ae6-a05c-e8c949524e94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Foto &amp; Document'])[1]/preceding::a[1]</value>
      <webElementGuid>fcafad19-4956-4f47-9dd9-a9e7e1093a07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[2]/a</value>
      <webElementGuid>b02d0b07-a311-4e3f-9166-1db45fe42124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'pr_id_202_header_1' and (text() = 'Medical Plan' or . = 'Medical Plan')]</value>
      <webElementGuid>e602dbbc-579d-42a7-9e60-7fddff14d2f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
