<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_product_service</name>
   <tag></tag>
   <elementGuidId>bfedee69-f6a5-4351-a04c-12aca80b7ba3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.p-dropdown-label.p-inputtext.p-placeholder</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='productServiceId']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ed48ae3a-9fb5-445c-841f-5e0065f75335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-dropdown-label p-inputtext p-placeholder</value>
      <webElementGuid>71bf1087-b40c-471c-8e74-eb9788f37a2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search...</value>
      <webElementGuid>f90d9fe0-c0a1-43d3-be85-ce8899fb714d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productServiceId&quot;)/span[@class=&quot;p-dropdown-label p-inputtext p-placeholder&quot;]</value>
      <webElementGuid>02b9adf7-b344-44ac-80c8-6c2165a8ef69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='productServiceId']/span</value>
      <webElementGuid>f513d566-de4c-4609-8e02-3cb7fe381280</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Service'])[2]/following::span[1]</value>
      <webElementGuid>a8e8c9b7-1cd5-412d-ad8a-ed4783d7930a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reguler Treatment'])[2]/following::span[2]</value>
      <webElementGuid>71cd294e-9748-452a-883b-91903ae875e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Medical Staff'])[1]/preceding::span[2]</value>
      <webElementGuid>cb3d6793-8b78-4ad4-8e24-ffe646b73107</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Doctor'])[1]/preceding::span[2]</value>
      <webElementGuid>00afe410-1d40-4f13-9bf7-ff284fef8ac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/div[2]/div[2]/div/span</value>
      <webElementGuid>4c408bba-9273-4576-b92f-7eb3625e5cbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Search...' or . = 'Search...')]</value>
      <webElementGuid>b62b3232-14af-40b2-a4a8-12e8437026f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
