<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textbox_interval</name>
   <tag></tag>
   <elementGuidId>aa6032c9-b622-45ec-9992-f72a93b7ce24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#interval</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='interval']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e0a873cc-2aca-4813-80b3-1ba505a0e68b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component input-text text-right</value>
      <webElementGuid>4208863a-b4c7-4d77-ba01-40ed5ad34b66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>interval</value>
      <webElementGuid>f8bda03d-7308-4f92-8e5a-9bb4f7fd205f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>interval</value>
      <webElementGuid>3cfd540b-6231-4797-a3ea-d4c1f0d2463b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;interval&quot;)</value>
      <webElementGuid>465e1592-3874-42e8-a401-6d7b97cb9280</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='interval']</value>
      <webElementGuid>a6cd8830-bc01-45aa-92cb-fed0ff3afae4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_245_content']/div/div[2]/div[5]/div[2]/div/div[2]/input</value>
      <webElementGuid>22982364-9a54-42c9-a4b2-5d15128bffea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div[2]/input</value>
      <webElementGuid>8cb02ddb-d8db-447f-900c-8fe71e8bfcbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'interval' and @placeholder = 'interval']</value>
      <webElementGuid>80867827-ff13-46fb-9dbd-186610ae7870</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
