<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Document</name>
   <tag></tag>
   <elementGuidId>2d0a1c2a-b885-4dfb-93ff-5d0b20a6db81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pr_id_20_header_1</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Document' or . = 'Document')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='pr_id_20_header_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>63715345-053f-48a4-8e9c-3a3a141f205f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pr_id_20_header_1</value>
      <webElementGuid>ca48b5a7-b8ea-4a99-a087-f8ff1d06521b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>275a97fb-6b85-4c2f-9976-49f2efa4f972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-tabview-nav-link</value>
      <webElementGuid>fc9a8b60-70e0-4ed1-9cbc-eedad34b677b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>eeee8b24-0c65-4450-9860-0d8e048d9ea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>pr_id_20_content_1</value>
      <webElementGuid>4bce4238-3374-4976-8116-b391dda1e5ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f3879a40-8fa4-494e-b572-a87d36490652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>headeraction</value>
      <webElementGuid>64218489-b61b-4d76-9341-1aa8e1084f71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Document</value>
      <webElementGuid>92381068-a5dd-4bfa-8b5e-0d9919f5cc9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_20_header_1&quot;)</value>
      <webElementGuid>899ddb64-8208-4cc1-afbe-29b3e7ef919a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='pr_id_20_header_1']</value>
      <webElementGuid>6e469ecb-2fe0-4f08-91bf-3fa4e766640b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_20']/ul/li[2]/a</value>
      <webElementGuid>608a1182-1b05-4811-8926-627979a57f72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/following::a[1]</value>
      <webElementGuid>67f4f613-f554-48d3-9226-e7c4a145a8c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preference Note'])[1]/following::a[2]</value>
      <webElementGuid>8ea4020a-4b73-40ff-acae-934c3acdaef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guarantor'])[1]/preceding::a[1]</value>
      <webElementGuid>4097d8db-436b-4039-821e-3232c8b57231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[2]/a</value>
      <webElementGuid>2ae72be7-bf55-4a43-9a26-e0ef9c8456e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'pr_id_20_header_1' and (text() = 'Document' or . = 'Document')]</value>
      <webElementGuid>3aa7e5a8-d528-499d-a43b-ea5944e27aab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
