<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add</name>
   <tag></tag>
   <elementGuidId>35183853-fc3a-41b2-bfe9-ed1f4d87e895</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.p-button.p-component.justify-content-center.button-action-add.text-body-2-white</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[(text() = 'Add' or . = 'Add')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pr_id_20_content_1']/div/div[2]/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b24524ac-0913-4b7c-b9a9-085201d01dff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>2e5643be-ca92-45dc-bfe9-b88d1979c02d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-button p-component justify-content-center button-action-add text-body-2-white</value>
      <webElementGuid>f6b5d4ab-5b55-4aba-b9ad-ea1a25176433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>64c0acab-ce69-409c-8968-371073843f99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>3485cca8-2d37-4d73-9789-0cfe66c7c10a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>6dab21a0-32d5-442c-95aa-3941e6b0d3e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_20_content_1&quot;)/div[@class=&quot;flex flex-row-reverse flex-wrap&quot;]/div[@class=&quot;flex align-items-center justify-content-center text-gray-900 m-2&quot;]/div[@class=&quot;block undefined&quot;]/div[1]/button[@class=&quot;p-button p-component justify-content-center button-action-add text-body-2-white&quot;]</value>
      <webElementGuid>edc5315a-f600-45b3-bfd0-81126387e28a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_20_content_1']/div/div[2]/div/div/button</value>
      <webElementGuid>3083cdab-efef-4435-aa33-69462ba7b6d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/following::button[1]</value>
      <webElementGuid>43e807d5-eeef-4d1e-8376-0ca5652fdf04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Membership'])[1]/following::button[2]</value>
      <webElementGuid>c0f9ec08-3d99-4d98-90d2-53c546e03166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::button[2]</value>
      <webElementGuid>04f73b1f-8b23-440d-8ce1-235ea52000d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button</value>
      <webElementGuid>35680162-fbcc-421d-8d31-66150860d89b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Add' or . = 'Add')]</value>
      <webElementGuid>8ad107a7-2e60-4e10-aae6-7adb54830d12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
