<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_docDescription</name>
   <tag></tag>
   <elementGuidId>e0db8499-62d2-437d-a3b8-cc34e0a21bb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea.p-inputtextarea.p-inputtext.p-component.p-inputtextarea-resizable.input-text-area.input-text-area</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//textarea[@id = 'textarea_docDescription']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[5]/div/div/div[2]/div/div/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>b89d7ed7-9de9-4ba6-b714-cdd2ad0e4629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtextarea p-inputtext p-component p-inputtextarea-resizable input-text-area input-text-area</value>
      <webElementGuid>6244c4ee-13ae-4bee-8c44-c6446900e590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>8b9586f0-cf61-4862-a874-5f660b79141d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>e8f73a58-d685-4852-88c3-82b59b8dc874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>inputtextarea</value>
      <webElementGuid>0b115902-ea5f-4d34-95b4-f936c7db89c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>660e663b-7cea-4f7e-bb67-be526f5b1d12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_12_content&quot;)/div[@class=&quot;col-12 p-0 my-2&quot;]/div[@class=&quot;flex flex-row flex-wrap justify-content-center&quot;]/div[@class=&quot;grid col-12 align-items-center p-0 m-0&quot;]/div[@class=&quot;col-8 p-0&quot;]/div[@class=&quot;grid row-gap-3 col-12 p-0 justify-content-between m-0&quot;]/div[@class=&quot;col-12 align-items-center text-value border-round p-0&quot;]/textarea[@class=&quot;p-inputtextarea p-inputtext p-component p-inputtextarea-resizable input-text-area input-text-area&quot;]</value>
      <webElementGuid>09718c8c-3c3a-42d0-a236-4114326c5090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textarea_docDescription</value>
      <webElementGuid>f9ce95e0-3aa8-4100-b1a1-4ce59a8fb142</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_12_content']/div[5]/div/div/div[2]/div/div/textarea</value>
      <webElementGuid>d4bad8e3-2449-47e8-83d1-0163f45eede5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/div/div/textarea</value>
      <webElementGuid>9de7e87d-f3f5-41c6-a37d-882b519321e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
