<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>toogle_Isdentity</name>
   <tag></tag>
   <elementGuidId>202de44b-fff0-482c-9d79-178df243e99b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;pr_id_23_content&quot;)/div[@class=&quot;col-12 p-0 my-2&quot;]/div[@class=&quot;flex flex-row flex-wrap justify-content-center&quot;]/div[@class=&quot;grid col-12 align-items-center p-0 m-0&quot;]/div[@class=&quot;col-8 p-0&quot;]/div[@class=&quot;grid row-gap-3 col-12 p-0 justify-content-between m-0&quot;]/div[@class=&quot;flex col-12 align-items-center text-value border-round p-0&quot;]/div[@class=&quot;p-inputswitch p-component toggle-switch&quot;]/span[@class=&quot;p-inputswitch-slider&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div[2]/div[2]/div/div/div[2]/div/div/div[1]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>42646dc4-5b4c-4c9e-8d3f-3cc9366bc16c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputswitch-slider</value>
      <webElementGuid>af081581-843c-4e51-ae9e-d230b31cf9e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>slider</value>
      <webElementGuid>5e49148b-9eb7-407a-a407-c3d8b8486ae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_23_content&quot;)/div[@class=&quot;col-12 p-0 my-2&quot;]/div[@class=&quot;flex flex-row flex-wrap justify-content-center&quot;]/div[@class=&quot;grid col-12 align-items-center p-0 m-0&quot;]/div[@class=&quot;col-8 p-0&quot;]/div[@class=&quot;grid row-gap-3 col-12 p-0 justify-content-between m-0&quot;]/div[@class=&quot;flex col-12 align-items-center text-value border-round p-0&quot;]/div[@class=&quot;p-inputswitch p-component toggle-switch&quot;]/span[@class=&quot;p-inputswitch-slider&quot;]</value>
      <webElementGuid>24ea6dcc-9ba5-4a1b-914e-e7eb0752ea44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_21_content']/div[2]/div/div/div[2]/div/div/div/span</value>
      <webElementGuid>6439f498-6005-44fb-93e8-570e8060c60f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div[2]/div/div/div/span</value>
      <webElementGuid>69608223-68f2-4c47-9e4a-b1cc03666e35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
