<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textbox_product_service</name>
   <tag></tag>
   <elementGuidId>ffde67d3-03be-4426-b699-624c9f64e32e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.p-inputtext.p-component.relative.input-search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c2cfa9ed-e176-4e91-9cac-568285cb24b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component relative input-search</value>
      <webElementGuid>38bb7c94-ca60-485e-99ad-065b1da3ac6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>ecb844c6-786a-41d4-a97d-3f6efc20e249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_47_content&quot;)/div[@class=&quot;grid m-0&quot;]/div[@class=&quot;col-12 md:col-6&quot;]/div[@class=&quot;grid&quot;]/div[@class=&quot;col-4 md:col-4 lg:col-5 xl:col-3 p-0&quot;]/div[@class=&quot;p-inputgroup w-full h-33&quot;]/input[@class=&quot;p-inputtext p-component relative input-search&quot;]</value>
      <webElementGuid>685c2860-7df0-4cec-b826-5b49356d5851</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[2]</value>
      <webElementGuid>9c1d67e0-a96b-4107-812e-1ded62966856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_47_content']/div/div/div/div[2]/div/input</value>
      <webElementGuid>0c1b1e57-4b3b-4255-9a3f-35d3432b3734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/input</value>
      <webElementGuid>d9b54b36-d50d-40f5-b1a8-3501ce2a7504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Search']</value>
      <webElementGuid>9c7dee99-e393-4637-8d88-b97eb83cc90d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
