<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_item_used</name>
   <tag></tag>
   <elementGuidId>1db0a2f1-c0df-4f4c-8f6d-7cfe9afee1cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pr_id_139_header_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='pr_id_139_header_1']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@role = 'tab' and (text() = 'Item Used' or . = 'Item Used')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1dd31a02-0027-44b5-80c9-648baa6f3d83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>83c11817-a8a8-4d6c-a87d-b0319b0a7aeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-tabview-nav-link</value>
      <webElementGuid>13740a9d-0840-41ab-92c3-42b14b53f25a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pr_id_139_header_1</value>
      <webElementGuid>4d3a5141-576b-494f-8c10-cd91a292e100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>pr_id_139_content_1</value>
      <webElementGuid>00486f08-cf48-4ff1-92cf-b3f7ad05109b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4982dd92-9b81-49df-96b4-0a403ba5f7ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d3083d2c-89d5-4e6b-80b3-94068ae0ff31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Item Used</value>
      <webElementGuid>f909427f-372d-4dbd-849e-debae42e3fe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_139_header_1&quot;)</value>
      <webElementGuid>4f92060f-47e8-45cb-b0c2-d3abf4a69160</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='pr_id_139_header_1']</value>
      <webElementGuid>d745c247-e9f0-407a-a80f-afedf2213953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_139']/ul/li[2]/a</value>
      <webElementGuid>a233f17c-ff80-432c-a4ac-f480fa897fd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Treatment Log Book'])[1]/following::a[1]</value>
      <webElementGuid>a69eac2b-e129-4860-bb7f-0ac548c46b87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Foto &amp; Document'])[1]/preceding::a[1]</value>
      <webElementGuid>b747cf03-1baf-4182-9484-28c0ebd50e1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[2]/a</value>
      <webElementGuid>5a2e2962-9d09-4dab-a132-01644cbbd94f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'pr_id_139_header_1' and (text() = 'Item Used' or . = 'Item Used')]</value>
      <webElementGuid>1ff7b3da-2dc2-428b-908d-2d78a83b3ba9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
