<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_item</name>
   <tag></tag>
   <elementGuidId>6fc1c0b8-afc3-422b-b595-eabe52c87681</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.p-dropdown-label.p-inputtext.p-placeholder</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pr_id_170_content']/form/div/div/div/div/div/div/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//span[@class = 'p-dropdown-label p-inputtext p-placeholder' and (text() = 'Choose' or . = 'Choose')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5bb1da54-637e-4b5d-b979-131aa2f526e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-dropdown-label p-inputtext p-placeholder</value>
      <webElementGuid>47edb52d-739d-45ba-a8b4-a91cec7647bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose</value>
      <webElementGuid>30322610-4af5-474c-93bb-f4ef91a82dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_170_content&quot;)/form[1]/div[@class=&quot;grid mt-2&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;p-fluid&quot;]/div[@class=&quot;field grid&quot;]/div[@class=&quot;col-12 md:col-9&quot;]/div[@class=&quot;p-dropdown p-component p-inputwrapper input-dropdown&quot;]/span[@class=&quot;p-dropdown-label p-inputtext p-placeholder&quot;]</value>
      <webElementGuid>7aab3ab8-cf71-430a-bcba-0ee98cdc6cc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_170_content']/form/div/div/div/div/div/div/span</value>
      <webElementGuid>82c1a326-fef0-4657-bbe3-5a3c51d1b991</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Item'])[2]/following::span[1]</value>
      <webElementGuid>98d89d80-cbf8-4b05-a6a9-9e69d9957057</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Item Used'])[1]/following::span[2]</value>
      <webElementGuid>caece0c4-4ab9-4ebf-83be-79de388c500e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity'])[2]/preceding::span[2]</value>
      <webElementGuid>453cdb44-31af-4119-953e-f34bc7011c71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='is Charge'])[2]/preceding::span[2]</value>
      <webElementGuid>2b480057-c941-4c32-bdea-73693edcd17e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div/div/span</value>
      <webElementGuid>ce9d98df-08cd-49f4-9d8f-55c9dd27cba9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Choose' or . = 'Choose')]</value>
      <webElementGuid>29a6f2ad-a5c0-40e3-9bf1-83fcd3edde56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
