<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Item Used</name>
   <tag></tag>
   <elementGuidId>db43ef4d-9665-4e43-b812-d0cf8c327575</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pr_id_269_header_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='pr_id_269_header_2']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@role = 'tab' and @class = 'p-tabview-nav-link' and (text() = 'Item Used' or . = 'Item Used')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dd99f73d-c778-44f1-bb5b-15bdf5acad53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>1c191229-211a-494b-8019-5e81d379828b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-tabview-nav-link</value>
      <webElementGuid>6116bc31-a4c4-45bf-a27e-5b9f4c6b8f3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pr_id_269_header_2</value>
      <webElementGuid>2644d936-9f56-4ee9-afa7-e5b1e5b5a0ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>pr_id_269_content_2</value>
      <webElementGuid>99a3099d-2fcd-47a0-ad28-cf06a10ac03e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>953b6dbd-5bdc-431a-9347-fc3fd2fcdf7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>72d0cd16-a035-4262-8e21-7af9d6889237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Item Used</value>
      <webElementGuid>a7abfdcb-1862-4285-a258-f25d7788fe88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_269_header_2&quot;)</value>
      <webElementGuid>a30bbaa8-be27-41c0-9205-06d0236eb39d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='pr_id_269_header_2']</value>
      <webElementGuid>393d663d-5f0a-4b8d-9e53-e3c8ad257eb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_269']/ul/li[3]/a</value>
      <webElementGuid>f3519e96-7013-43b6-83f8-c67a12d2e4d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Treatment Log Book'])[1]/following::a[1]</value>
      <webElementGuid>7dad351c-344d-483a-8fab-ec130e159b1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diagnosis'])[1]/following::a[2]</value>
      <webElementGuid>ac965be5-1e41-4154-ac95-780628c5e5cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Photo &amp; Document'])[1]/preceding::a[1]</value>
      <webElementGuid>a764bab9-e2a9-4b51-a315-2a1a5741bf1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[3]/a</value>
      <webElementGuid>c93d9119-3823-448f-ad3d-a10c2fe15c7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'pr_id_269_header_2' and (text() = 'Item Used' or . = 'Item Used')]</value>
      <webElementGuid>c1cbf162-5947-4b27-bca0-fd6a4d067b22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
