<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Treatment Log Book</name>
   <tag></tag>
   <elementGuidId>9e6d4111-2ff4-41e1-96f2-7260f46abd0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@role = 'tab' and @class = 'p-tabview-nav-link' and (text() = 'Treatment Log Book' or . = 'Treatment Log Book')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pr_id_269_header_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='pr_id_269_header_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>aba9e0f2-1ba4-4acb-9907-eedf2ba48442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>2b38fbd3-bc4f-4a2f-a289-8c4b7471caf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-tabview-nav-link</value>
      <webElementGuid>c10cc553-f9f6-46e2-93ec-1127eb69f5f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pr_id_269_header_1</value>
      <webElementGuid>8b0f2577-c633-439a-9fc0-b1b5abdb87d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>pr_id_269_content_1</value>
      <webElementGuid>a6685af9-c2c4-4473-9130-a3eebb12ffc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a31cb9be-036a-4907-97ef-33e4533a0588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>194cf202-692c-4722-85e5-a0736c71786c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Treatment Log Book</value>
      <webElementGuid>598ad478-a3d1-4d16-9da7-916df4890cfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_269_header_1&quot;)</value>
      <webElementGuid>ba3c8907-5a98-4e33-b318-94f0cb304992</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='pr_id_269_header_1']</value>
      <webElementGuid>f6419e06-40a1-4419-9536-9be2896d2fa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_269']/ul/li[2]/a</value>
      <webElementGuid>0a4d4eaa-75b2-4cc6-ba32-f6d320921fb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diagnosis'])[1]/following::a[1]</value>
      <webElementGuid>6a19bac1-6c95-465c-b19f-970c50f116f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Item Used'])[1]/preceding::a[1]</value>
      <webElementGuid>90f4f55f-4e50-4d30-bbbc-7b6335da1c8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[2]/a</value>
      <webElementGuid>e5f8aa3f-a027-4f75-8bc0-f1bbc451273a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'pr_id_269_header_1' and (text() = 'Treatment Log Book' or . = 'Treatment Log Book')]</value>
      <webElementGuid>4f5e4bda-4200-4ec8-9f23-67b771baf996</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
