<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_note</name>
   <tag></tag>
   <elementGuidId>bf0fbdad-6adc-4ab5-a8ca-1acb91a4bbf0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//textarea[@placeholder = 'Note' and @class = 'p-inputtextarea p-inputtext p-component p-inputtextarea-resizable input-text-area-notes']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pr_id_269_content_1']/div/form/div[2]/div[2]/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>8222b700-c951-4f4e-90da-f13e8470256a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Note</value>
      <webElementGuid>1e03fa09-955b-4262-b565-9061ccf81b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtextarea p-inputtext p-component p-inputtextarea-resizable input-text-area-notes</value>
      <webElementGuid>14b91b6a-bfe7-413f-bcc0-83262b16b701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>e489c168-31fe-4954-9e00-e6ea413f531b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>385b8145-97d8-46d9-aebb-3c40f4beb024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>585e0e86-2b54-498d-b64b-0ae6655edf03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_269_content_1&quot;)/div[@class=&quot;p-blockui-container&quot;]/form[1]/div[@class=&quot;grid formgrid col-12 p-0&quot;]/div[@class=&quot;col-12 md:col-10&quot;]/textarea[@class=&quot;p-inputtextarea p-inputtext p-component p-inputtextarea-resizable input-text-area-notes&quot;]</value>
      <webElementGuid>ebb51e00-69e7-47b4-be55-d17a7dcf7c27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_269_content_1']/div/form/div[2]/div[2]/textarea</value>
      <webElementGuid>22ba1d97-16dd-45f0-8f04-c18da0773815</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/textarea</value>
      <webElementGuid>be6037b5-7f82-4046-9d90-1ac0bbbba89d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Note']</value>
      <webElementGuid>041ff441-7945-43cd-90ed-8aed7159edb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
