<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_referal_doctor</name>
   <tag></tag>
   <elementGuidId>70d82e5b-b3a3-4e23-a933-3341a9e88b9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='medicalStaffId']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.p-dropdown-label.p-inputtext.p-placeholder</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e2676fa3-185a-479d-8e52-1baf95778115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-dropdown-label p-inputtext p-placeholder</value>
      <webElementGuid>2ab0b50e-7e5c-4fff-8e40-60b76820bbdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search...</value>
      <webElementGuid>aef7aa8b-29fa-402a-b712-22956b5dabdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;medicalStaffId&quot;)/span[@class=&quot;p-dropdown-label p-inputtext p-placeholder&quot;]</value>
      <webElementGuid>57166191-ece9-4f3f-b883-09d001867659</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='medicalStaffId']/span</value>
      <webElementGuid>0c11a45c-8cb5-47a5-a4df-136f837465f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Referral Doctor'])[2]/following::span[1]</value>
      <webElementGuid>ae2b51e5-4a1d-42f8-be55-1abb88a2f7f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*Valid for 1 month only'])[1]/following::span[1]</value>
      <webElementGuid>863320c8-9ff6-4fa6-8a82-c1313edcbcae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service Activity'])[5]/preceding::span[2]</value>
      <webElementGuid>875367d9-725e-4f89-845e-852d4b4005f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose activity'])[2]/preceding::span[2]</value>
      <webElementGuid>54533bc1-6617-4084-a616-853f624953d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/span</value>
      <webElementGuid>af06a016-c6bf-4198-92be-0ef0e7cde3c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Search...' or . = 'Search...')]</value>
      <webElementGuid>b2558b3d-0831-49b4-89f7-d76af3ff4283</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
