<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_letter_type</name>
   <tag></tag>
   <elementGuidId>c689681c-c2f8-4f4a-a58b-bbd77b9a4647</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='letterType']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.p-dropdown-label.p-inputtext.p-placeholder</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dbc18cef-61dd-4dde-a530-7aa140e584d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-dropdown-label p-inputtext p-placeholder</value>
      <webElementGuid>af9a098e-8ebd-4e37-b819-37ed06742a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose Type</value>
      <webElementGuid>1a411dc5-6204-4dae-afb9-3eedcb111166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;letterType&quot;)/span[@class=&quot;p-dropdown-label p-inputtext p-placeholder&quot;]</value>
      <webElementGuid>fb084559-88d2-4990-acab-d8508a8e51e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='letterType']/span</value>
      <webElementGuid>fac195b8-9dda-4bed-baee-37f16d049dfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Letter Type'])[2]/following::span[1]</value>
      <webElementGuid>040ea20e-6f18-4c5a-9860-c248aac32924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Referral Detail'])[1]/following::span[2]</value>
      <webElementGuid>e42e008b-d48e-4330-9202-814afcef3231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Referral Branch'])[2]/preceding::span[2]</value>
      <webElementGuid>929e8643-f17d-4caa-8406-fa66dd6b02d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Klinik Utama Erha Ultimate BSD'])[5]/preceding::span[2]</value>
      <webElementGuid>2e6fbc3f-b7ba-46f3-b54a-b3adb866cf5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/div/div[2]/div/span</value>
      <webElementGuid>06ceeeb5-c43b-4f77-a344-2c0469575efa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Choose Type' or . = 'Choose Type')]</value>
      <webElementGuid>87765118-e981-4b7a-947c-47d1fa7f791c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
