<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_diagnose</name>
   <tag></tag>
   <elementGuidId>53d647c1-f009-4ded-baa0-75997af38d3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='diagnose']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#diagnose</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>8483786d-bf00-4457-9b42-5965ab7c83a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtextarea p-inputtext p-component p-inputtextarea-resizable input-text-area</value>
      <webElementGuid>e5508c37-eac7-458b-9af7-a5ecd2816644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>bcba871f-b52e-41df-bb18-b98d904c6ef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>diagnose</value>
      <webElementGuid>e5290473-c508-41d5-81ed-c898925f4fac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>36b02b0a-884e-46d4-834b-73c3e0345a8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input diagnose</value>
      <webElementGuid>f6ad3db1-c553-4887-98ec-f2084add8ceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;diagnose&quot;)</value>
      <webElementGuid>ecffb8fd-ea40-40f9-8c6e-ae9195cfda95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='diagnose']</value>
      <webElementGuid>b655aeee-4f93-4c5b-bcc0-913cbeddca42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_196_content']/div/div[2]/div[2]/div[2]/textarea</value>
      <webElementGuid>5a722868-f13f-49c5-895f-561a57b276c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/textarea</value>
      <webElementGuid>8ab88087-3757-4acc-9354-54e2555e4617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'diagnose' and @placeholder = 'Input diagnose']</value>
      <webElementGuid>54896433-ef63-4a2f-b9c6-d07edbb67e9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
