<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textbox_interval</name>
   <tag></tag>
   <elementGuidId>fd4b4145-165f-47b7-8030-b56ca89bcfa0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='interval']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#interval</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a82b7177-49d2-4e62-bfd4-4b94f957dde7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component input-text text-right</value>
      <webElementGuid>a5f12617-fde1-42e0-b50e-dc7ff45a3c9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>interval</value>
      <webElementGuid>a64d9d75-33dd-4a14-ab22-522ffc029f96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>interval</value>
      <webElementGuid>1081cfc0-6100-4f9a-8a66-655db71a4906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;interval&quot;)</value>
      <webElementGuid>094e5a2f-91cf-4eb2-896a-dc7c745725ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='interval']</value>
      <webElementGuid>828ee396-0e3b-4c3e-8384-c571c4f5df4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_196_content']/div/div[2]/div[4]/div[2]/div/div[2]/input</value>
      <webElementGuid>d6362fdb-aed8-4e93-afce-2c0926206b2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div[2]/input</value>
      <webElementGuid>3c8fda8a-5f3f-4030-a551-23d6cab4e21d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'interval' and @placeholder = 'interval']</value>
      <webElementGuid>b7ebbc86-4663-4eb2-86c9-86bc5fed324c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
