<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_product_service</name>
   <tag></tag>
   <elementGuidId>5da5b007-b017-4359-bad7-18ce8cba9ebb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.p-autocomplete-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='pr_id_213_list']/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>34c39145-0408-4d39-acac-43e8dd356223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>3d7e37fe-7211-44dc-a3a3-dccbbe0d5b5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e0f46681-a40e-4a4f-b433-2493d2922854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-autocomplete-item</value>
      <webElementGuid>304f93b8-c47b-4bef-9224-df0246ca7146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ABS 2.5 - ABS + BPO 2.5% 60 ml - 199.998</value>
      <webElementGuid>3d6b8b69-9a76-43f3-bfcd-24ae73c77307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_213_list&quot;)/li[@class=&quot;p-autocomplete-item&quot;]</value>
      <webElementGuid>542196d0-1ea9-498e-ba32-a0d11fde42f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='pr_id_213_list']/li</value>
      <webElementGuid>821b449b-c92f-4ac6-bd7e-816fabdfced7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 0 to 0 of 0'])[1]/following::li[1]</value>
      <webElementGuid>45628b97-cd83-4bbf-a58d-31653bc15383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No results found'])[2]/following::li[1]</value>
      <webElementGuid>edc98326-be04-47ca-8cdf-c1cf789934d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ABS 2.5 - ABS + BPO 2.5% 60 ml - 199.998']/parent::*</value>
      <webElementGuid>d74d509a-0236-4322-9216-28132605b512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul/li</value>
      <webElementGuid>17d465a9-277d-4907-b545-5de5cd0425c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'ABS 2.5 - ABS + BPO 2.5% 60 ml - 199.998' or . = 'ABS 2.5 - ABS + BPO 2.5% 60 ml - 199.998')]</value>
      <webElementGuid>c36ddfb6-7b85-4c85-85b6-504b2d169d1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
