<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textbox_remarks</name>
   <tag></tag>
   <elementGuidId>da016021-e3da-4a06-93d1-c2b91a6caf08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#remarks</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='remarks']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>45971cfb-5e9e-449c-850c-661d537a2a72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component input-text</value>
      <webElementGuid>5d27fa62-a805-49f8-94ad-33ddac023417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>remarks</value>
      <webElementGuid>510de35e-894b-447c-99ac-31d3b7d2efc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input Remarks</value>
      <webElementGuid>fa213826-c452-4a21-bdbe-2d5ed609c203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;remarks&quot;)</value>
      <webElementGuid>bc88a9e2-db47-485c-95fc-ece6df532f12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='remarks']</value>
      <webElementGuid>b7a66c13-b40d-4efe-a9dd-79406f63e5dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_683_content']/div/div/form/div/div[2]/div[4]/div[2]/input</value>
      <webElementGuid>cd02392c-8553-4d09-8bd0-5ff762f21b4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div[4]/div[2]/input</value>
      <webElementGuid>3c6c93af-7c18-43d6-8cbb-5356df4b8bbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'remarks' and @placeholder = 'Input Remarks']</value>
      <webElementGuid>ba986736-3ed4-4ee0-b310-2ad3749801d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
