<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textbox_signa</name>
   <tag></tag>
   <elementGuidId>a79a1e4b-4a19-4516-a5ac-f67bc2fdce75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#howToUse</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='howToUse']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a19eea73-b695-4427-a98c-51cb1f557789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component input-text</value>
      <webElementGuid>f62c732a-6c07-4b02-8dda-c6bb39395d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>howToUse</value>
      <webElementGuid>a8d5568f-598c-4526-ad31-2cc54ef248f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>27f8d1aa-9920-4796-9b54-e428a54be7c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input notes</value>
      <webElementGuid>fdd3d178-ce5f-4293-ad90-b545171fadb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;howToUse&quot;)</value>
      <webElementGuid>08b4f7a0-8747-4da7-a4ee-3f6d0db8c064</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='howToUse']</value>
      <webElementGuid>675ade30-8353-4656-baee-e2f5226b129c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_683_content']/div/div/form/div/div[2]/div[2]/div[2]/input</value>
      <webElementGuid>a4b3166a-9374-499d-b0bd-5a75400f860d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div[2]/div[2]/input</value>
      <webElementGuid>4166fe3d-0205-41c0-a410-2feb36b4ee6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'howToUse' and @type = 'text' and @placeholder = 'Input notes']</value>
      <webElementGuid>14cbec05-7749-400c-a7d0-4c28f7273eec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
