<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textbox_iter</name>
   <tag></tag>
   <elementGuidId>7801c05d-6342-4fb0-9766-0ebbe8123d85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#iter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='iter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f66c93a0-70a6-47ca-a72a-05644b6bfa0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-filled input-text text-right</value>
      <webElementGuid>a1db1b2f-5ffd-4c5b-af3f-172e29abe5a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iter</value>
      <webElementGuid>bfa9db1d-4772-43f7-9039-475b9b9728e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>adeb3a23-4565-4e51-af53-d2356b5cfbfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter amount</value>
      <webElementGuid>57c12baf-665d-4e5b-9132-c6c231d96156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a39c7d1b-6268-41ac-8fae-75fd219e04d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iter&quot;)</value>
      <webElementGuid>b761c792-6f35-46c7-b078-732c7286c5b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='iter']</value>
      <webElementGuid>9da64090-40c4-48c4-8768-d2ca0bdc70ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_683_content']/div/div/form/div/div[2]/div[3]/div[2]/input</value>
      <webElementGuid>81a61c28-5c17-4666-acc5-0cddf1338404</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div[3]/div[2]/input</value>
      <webElementGuid>53059123-4508-4d24-a1e9-01748ec63904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'iter' and @type = 'number' and @placeholder = 'Enter amount']</value>
      <webElementGuid>bfbcd9d8-47d2-48f6-8cbd-07c7ff03e37c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
