<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_search</name>
   <tag></tag>
   <elementGuidId>19cd110f-e38d-4215-a915-8d8ab6a3a63d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pr_id_47_content']/div/div[2]/div/div[2]/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ca9fd7f9-bcf6-4cab-b9f7-e88129f8c0d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-button p-component bg-border-blue p-button-icon-only</value>
      <webElementGuid>850b038c-a23e-42e3-a567-b5f13adfb9e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>903f84cf-b471-48df-bf5f-8186bd89c113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_47_content&quot;)/div[@class=&quot;grid m-0&quot;]/div[@class=&quot;col-12 md:col-6&quot;]/div[@class=&quot;grid&quot;]/div[@class=&quot;col-4 md:col-4 lg:col-5 xl:col-3 p-0&quot;]/div[@class=&quot;p-inputgroup w-full h-33&quot;]/button[@class=&quot;p-button p-component bg-border-blue p-button-icon-only&quot;]</value>
      <webElementGuid>b3f874ee-b88d-41a3-bf2c-1a45811d9c5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_47_content']/div/div[2]/div/div[2]/div/button</value>
      <webElementGuid>aa00fe15-d93a-45bf-9583-ab42a1f9515c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inventory List'])[1]/following::button[1]</value>
      <webElementGuid>73c60fc9-1d9d-4f60-822c-f407d0e37764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select'])[1]/following::button[3]</value>
      <webElementGuid>158fcbe0-ae9f-4162-801a-a58f1cd1ca41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[5]/preceding::button[1]</value>
      <webElementGuid>f6d59a81-97fe-4e3c-9d12-7afc1ee5a980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Category'])[2]/preceding::button[1]</value>
      <webElementGuid>c151531d-67d1-4d6e-b672-5f19e6f5ad41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div[2]/div/button</value>
      <webElementGuid>262721a2-e15f-46e1-8249-eb7fdb30e6b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' ' or . = ' ')]</value>
      <webElementGuid>a0b41e9e-52b8-4832-86ab-29fd2d68a201</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
