<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_assessment</name>
   <tag></tag>
   <elementGuidId>149aabfe-aee1-4698-81f9-2f38af4f726f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.p-button.p-component.absolute.bg-border-netral.netral-hover.search-button.p-button-icon-only</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pr_id_208_content_0']/div/div[2]/div[2]/div/div[2]/button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[@class = 'p-button p-component absolute bg-border-netral netral-hover search-button p-button-icon-only' and (text() = ' ' or . = ' ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>978c1d89-433a-406b-9398-450eb4137360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-button p-component absolute bg-border-netral netral-hover search-button p-button-icon-only</value>
      <webElementGuid>e89d649c-e300-42ac-9a78-3641702931ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>41134d1f-00b3-4880-8809-b1d4866036cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_208_content_0&quot;)/div[@class=&quot;p-blockui-container&quot;]/div[@class=&quot;grid mt-3&quot;]/div[@class=&quot;col pr-0&quot;]/div[@class=&quot;grid formgrid col-12 p-0 mb-2&quot;]/div[@class=&quot;relative col-12 md:col-8&quot;]/button[@class=&quot;p-button p-component absolute bg-border-netral netral-hover search-button p-button-icon-only&quot;]</value>
      <webElementGuid>bade6f62-a2ff-478b-911e-b1bab42b9ec8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_208_content_0']/div/div[2]/div[2]/div/div[2]/button</value>
      <webElementGuid>a2ed423d-c59a-4982-8591-6175d7f332ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::button[1]</value>
      <webElementGuid>6d80843d-6622-402d-aa59-bbbeeee7dbf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/preceding::button[1]</value>
      <webElementGuid>97b45077-9e25-4111-a0d4-f50d017da753</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>f95bd1a4-661c-46a0-afa7-c1b40d3f89a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' ' or . = ' ')]</value>
      <webElementGuid>f256cce8-d66b-4a4d-970f-9797523108cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
