<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_service_activity</name>
   <tag></tag>
   <elementGuidId>8ccc4de4-c07c-43d1-a75b-4c1031d84728</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.p-dropdown-label.p-inputtext.p-placeholder</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='serviceActivityId']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dbc3f924-bf27-4e45-83c7-80facbaaa328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-dropdown-label p-inputtext p-placeholder</value>
      <webElementGuid>c84a8295-481b-4d4f-8832-a3a72f66946e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose</value>
      <webElementGuid>8acaaa12-f4c6-413f-bab3-753d4bdcd224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;serviceActivityId&quot;)/span[@class=&quot;p-dropdown-label p-inputtext p-placeholder&quot;]</value>
      <webElementGuid>73705a0a-3d51-47fc-ab5e-4d6e98ccef77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='serviceActivityId']/span</value>
      <webElementGuid>49ea84c1-b66f-4256-b796-a40df5f69ab1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service Activity'])[6]/following::span[1]</value>
      <webElementGuid>fe394584-037f-4bcb-9c01-802b81e5fa3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service Activity'])[5]/following::span[2]</value>
      <webElementGuid>5bbd2cfe-a741-4201-924c-24bec9d865a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Service'])[2]/preceding::span[2]</value>
      <webElementGuid>60a8391a-c524-47c3-b70d-4675474f56a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search...'])[2]/preceding::span[2]</value>
      <webElementGuid>02755549-ffd4-4270-a96d-3043318b399a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/span</value>
      <webElementGuid>fe6a21f9-7e39-4034-a8a7-d4c6391d4ecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Choose' or . = 'Choose')]</value>
      <webElementGuid>10ca3544-5601-460a-8c04-914beb02aeb7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
